# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

_imagine:
    resource: .
    type:     imagine
    
admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
acme_main:
    resource: "@AcmeApplicationBundle/Controller/MainController.php"
    type: annotation